---
title: "Building Production-Quality Shiny Applications"
subtitle: "R/Pharma 2022 Workshop"
editor: source
---

------------------------------------------------------------------------

🗓️ November 3, 2022 \| 9:00am - 12:00pm EDT

🏨 Virtual

💥 **FREE** with [conference registration](https://hopin.com/events/r-pharma-2022/registration)

📝 To register for the workshop, visit <https://rinpharma.com/workshop/2022conference/>.

------------------------------------------------------------------------

# Overview

Shiny empowers R users to create innovative web applications, without requiring substantial expertise in web development frameworks to get up and running. The positive impact of Shiny in data science workflows across academia and a variety of industries such as life sciences is well-known and growing by the year. It is quite common for an early prototype of a Shiny app to generate tremendous excitement for key stakeholders and decision makers, often leading to requests for enhancements and ultimately be included in a production pipeline or process. The road to meeting this goal is challenging, especially for data scientists and statisticians not accustomed to software development! This workshop is for the Shiny developer who has entered this stage of their application development journey. The user is ready to learn how essential workflows, best practices, and the expanding community of Shiny-related packages can help them climb the ladder of Shiny development.

## Learning objectives

TODO: Add general description of course modules

## Is this course for me?

TODO: Copy most text from existing Shiny prod site

## Prework

TODO: Copy over setup instructions from existing Shiny prod site
 
# Instructor

TODO: Copy over bio from existing Shiny prod site
